name: Programming Challenge CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tests:
          - { name: ArmstrongNumbers }
          - { name: Brackets }
          - { name: Distincts }

    steps:
      # Checkout Commit
      - name: Checkout Branch
        uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Composer Cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run Tests
      - name: Run Test - ${{ matrix.tests.name }}
        run: composer run-script Test-${{ matrix.tests.name }}
