name: Programming Challenge CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - { name: Armstrong Numbers, test: ArmstrongNumbers }
          - { name: Brackets, test: Brackets }
          - { name: Distincts, test: Distincts }

    name: ${{ matrix.actions.name }} CI
    runs-on: ubuntu-latest

    steps:
      # Checkout Commit
      - name: Checkout Branch
        uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Composer Cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run PHP Coding Standards
      - name: ${{ matrix.actions.name }} PHP Coding Standards
        run: composer run-script ${{ matrix.actions.test }}-PhpStan

      # Run Easy Coding Standards
      - name: ${{ matrix.actions.name }} Easy Coding Standards
        run: composer run-script ${{ matrix.actions.test }}-Esc

      # Run Tests
      - name: ${{ matrix.actions.name }} Test
        run: composer run-script ${{ matrix.actions.test }}-Test
