name: Programming Challenge CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - { name: Armstrong Numbers Test, test: ArmstrongNumbers }
          - { name: Brackets Test, test: Brackets }
          - { name: Distincts Test, test: Distincts }

    name: Run ${{ matrix.actions.name }}
    runs-on: ubuntu-latest

    steps:
      # Checkout Commit
      - name: Checkout Branch
        uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Composer Cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run PHP Coding Standards
      - name: PHP Coding Standards
        run: vendor/bin/phpstan analyse src/${{ matrix.actions.test }} tests/ProgrammingChallenge/${{ matrix.actions.test }} --level=7

      # Run Tests
      - name: Run ${{ matrix.actions.name }}
        run: composer run-script Test-${{ matrix.actions.test }}
