name: Programming Challenge CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - { name: Armstrong Numbers, module: ArmstrongNumbers }
          - { name: Brackets, module: Brackets }
          - { name: Distincts, module: Distincts }

    name: ${{ matrix.actions.name }} Coding Standards & Test
    runs-on: ubuntu-latest

    steps:
      # Checkout Commit
      - name: Checkout Branch
        uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Composer Cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run PHP Coding Standards
      - name: PHP Coding Standards - ${{ matrix.actions.name }}
        run: composer run-script ${{ matrix.actions.module }}-PhpStan

      # Run Easy Coding Standards
      - name: Easy Coding Standards - ${{ matrix.actions.name }}
        run: composer run-script ${{ matrix.actions.module }}-Ecs

      # Run Tests
      - name: Unit Test - ${{ matrix.actions.name }}
        run: composer run-script ${{ matrix.actions.module }}-Test
