name: Programming Challenge CI

on:
  push:
    branches: [ master, develop ]

jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - { name: Test - ArmstrongNumber, run: composer run-script Test-ArmstrongNumbers }
          - { name: Test - Brackets, run: composer run-script Test-Brackets }
          - { name: Test - Distinct, run: composer run-script Test-Distincts }

    name: ${{ matrix.actions.name }}
    runs-on: ubuntu-latest

    steps:
      # Checkout Commit
      - name: Checkout Branch
      - uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Cache Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run Tests
      - name: ${{ matrix.actions.name }}
        run: ${{ matrix.actions.run }}