name: Programming Challenge CI

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test-name: [ 'Test - ArmstrongNumber', 'Test - Brackets', 'Test - Distinct' ]
        test-suite: [ 'ArmstrongNumbers', 'Brackets', 'Distinct' ]

    runs-on: ubuntu-latest

    steps:
      # Checkout Commit
      - name: Checkout Branch
      - uses: actions/checkout@v2

      # Validate Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # Cache Composer
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Install Dependency
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # Run Tests
      - name: ${{ matrix.test-name }}
        run: composer run-script Test-${{ matrix.test-suite }}
